### ISSUE TITLE
error: #error Code needs update for DTLS_method() support beyond DTLS1_VERSION.

### ISSUE THREAD

**Issue by iolalla** [pol51/OpenSSL-CMake#2]
Hi,
 I am trying to compile the project on a Ubuntu 16.04, g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413, OpenSSL 1.0.2g-fips  1 Mar 2016.
And I am getting all the time the error: #error Code needs update for DTLS_method() support beyond DTLS1_VERSION., when I try to compile, but not sure it is related to the openssl version or smth different.

Thanks for your help.

**Comment by pol51** [comment]
I had the same issue on Gentoo (and fixed it)
