### ISSUE TITLE
Build step not working on Windows VisualStudio 14 2015

### ISSUE THREAD

**Issue by Varser** [pol51/OpenSSL-CMake#6]
There are a lot of errors like {{fatal error C1083: Cannot open include file: 'openssl/e_os2.h': No such file or directory}} during the build.

**Comment by Lumak** [comment]
I had the same problem and fixed it in my fork.

**Comment by pol51** [comment]
@Varser fixed in version OpenSSL_1_0_1u_1-cmake

**Comment by Lumak** [comment]
tested MSVC build:
* set(BUILD_OBJECT_LIBRARY_ONLY OFF BOOL) is set which you cannot override from cmake-gui or command line. It used to be optional checkbox in cmake-gui when i created my fork.
* even if the above line is commented out and build object libs only, the header files you need are in three locations:
1- (build dir)/openssl
2- (build dir)/crypto/openssl
3- (build dir)/ssl/openssl
They should be consolidated into a single openssl folder.

**Comment by pol51** [comment]
@Lumak  I made some changes:
- all includes in ${CMAKE_BINARY_DIR}/include/openssl
- BUILD_OBJECT_LIBRARY_ONLY should appear as an option now

**Comment by Lumak** [comment]
Nice. Thank you!
